/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_des_troupeaux (void);
GtkWidget* create_Message_d_erreur (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_Rechercher (void);
GtkWidget* create_Modification (void);
GtkWidget* create_fenetre_afficher (void);
