/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Interface_o (void)
{
  GtkWidget *Interface_o;
  GtkWidget *fixed1;
  GtkWidget *buttonAfficher_o;
  GtkWidget *buttonModif_o;
  GtkWidget *buttonSupp_o;
  GtkWidget *buttonRec_o;
  GtkWidget *buttonAjout_o;
  GtkWidget *buttonControler_o;
  GtkWidget *labelTitle_o;

  Interface_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Interface_o), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Interface_o), fixed1);

  buttonAfficher_o = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (buttonAfficher_o);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAfficher_o, 520, 392);
  gtk_widget_set_size_request (buttonAfficher_o, 80, 32);

  buttonModif_o = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonModif_o);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonModif_o, 600, 328);
  gtk_widget_set_size_request (buttonModif_o, 80, 32);

  buttonSupp_o = gtk_button_new_with_mnemonic (_("Suppimer"));
  gtk_widget_show (buttonSupp_o);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSupp_o, 744, 328);
  gtk_widget_set_size_request (buttonSupp_o, 96, 32);

  buttonRec_o = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (buttonRec_o);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonRec_o, 664, 392);
  gtk_widget_set_size_request (buttonRec_o, 88, 32);

  buttonAjout_o = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonAjout_o);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjout_o, 448, 328);
  gtk_widget_set_size_request (buttonAjout_o, 72, 32);

  buttonControler_o = gtk_button_new_with_mnemonic (_("Controler"));
  gtk_widget_show (buttonControler_o);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonControler_o, 832, 392);
  gtk_widget_set_size_request (buttonControler_o, 88, 32);

  labelTitle_o = gtk_label_new (_("Gestion des ouvriers"));
  gtk_widget_show (labelTitle_o);
  gtk_fixed_put (GTK_FIXED (fixed1), labelTitle_o, 568, 16);
  gtk_widget_set_size_request (labelTitle_o, 168, 32);

  g_signal_connect ((gpointer) buttonAfficher_o, "clicked",
                    G_CALLBACK (on_buttonAfficher_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModif_o, "clicked",
                    G_CALLBACK (on_buttonModif_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupp_o, "clicked",
                    G_CALLBACK (on_buttonSupp_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRec_o, "clicked",
                    G_CALLBACK (on_buttonRec_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjout_o, "clicked",
                    G_CALLBACK (on_buttonAjout_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonControler_o, "clicked",
                    G_CALLBACK (on_buttonControler_o_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Interface_o, Interface_o, "Interface_o");
  GLADE_HOOKUP_OBJECT (Interface_o, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Interface_o, buttonAfficher_o, "buttonAfficher_o");
  GLADE_HOOKUP_OBJECT (Interface_o, buttonModif_o, "buttonModif_o");
  GLADE_HOOKUP_OBJECT (Interface_o, buttonSupp_o, "buttonSupp_o");
  GLADE_HOOKUP_OBJECT (Interface_o, buttonRec_o, "buttonRec_o");
  GLADE_HOOKUP_OBJECT (Interface_o, buttonAjout_o, "buttonAjout_o");
  GLADE_HOOKUP_OBJECT (Interface_o, buttonControler_o, "buttonControler_o");
  GLADE_HOOKUP_OBJECT (Interface_o, labelTitle_o, "labelTitle_o");

  return Interface_o;
}

GtkWidget*
create_Ajout_o (void)
{
  GtkWidget *Ajout_o;
  GtkWidget *fixed2;
  GtkWidget *entryNom;
  GtkWidget *entryCIN;
  GtkWidget *labelDNremarque;
  GtkWidget *labelCIN;
  GtkWidget *labelNom;
  GtkWidget *entryUser;
  GtkWidget *labelUser;
  GtkObject *spinbuttonJT_adj;
  GtkWidget *spinbuttonJT;
  GtkWidget *labelDN;
  GtkObject *spinbuttonJJDN_adj;
  GtkWidget *spinbuttonJJDN;
  GtkObject *spinbuttonMDN_adj;
  GtkWidget *spinbuttonMDN;
  GtkObject *spinbuttonADN_adj;
  GtkWidget *spinbuttonADN;
  GtkObject *spinbuttonJRec_adj;
  GtkWidget *spinbuttonJRec;
  GtkObject *spinbuttonMRec_adj;
  GtkWidget *spinbuttonMRec;
  GtkObject *spinbuttonARec_adj;
  GtkWidget *spinbuttonARec;
  GtkWidget *labelTitle;
  GtkWidget *comboboxSpec;
  GtkWidget *labelSpecial;
  GtkWidget *labelJT;
  GtkWidget *checkbuttonLundi_o;
  GtkWidget *checkbuttonMardi_o;
  GtkWidget *checkbuttonMercredi_o;
  GtkWidget *checkbuttonJeudi_o;
  GtkWidget *checkbuttonVendredi_o;
  GtkWidget *checkbuttonSamedi_o;
  GtkWidget *checkbuttonDimanche_o;
  GtkWidget *labelRec;
  GtkWidget *labelGenre;
  GtkWidget *radiobuttonH_o;
  GSList *radiobuttonH_o_group = NULL;
  GtkWidget *radiobuttonF_o;
  GtkWidget *buttonInscri_o;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label18;

  Ajout_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout_o), _("window1"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajout_o), fixed2);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed2), entryNom, 568, 128);
  gtk_widget_set_size_request (entryNom, 392, 32);
  gtk_entry_set_max_length (GTK_ENTRY (entryNom), 100);
  gtk_entry_set_text (GTK_ENTRY (entryNom), _("SVP Introduire nom"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 46);

  entryCIN = gtk_entry_new ();
  gtk_widget_show (entryCIN);
  gtk_fixed_put (GTK_FIXED (fixed2), entryCIN, 568, 168);
  gtk_widget_set_size_request (entryCIN, 392, 32);
  gtk_entry_set_max_length (GTK_ENTRY (entryCIN), 12);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCIN), 8226);

  labelDNremarque = gtk_label_new (_("(SVP respecter le format demand\303\251)"));
  gtk_widget_show (labelDNremarque);
  gtk_fixed_put (GTK_FIXED (fixed2), labelDNremarque, 296, 232);
  gtk_widget_set_size_request (labelDNremarque, 280, 24);

  labelCIN = gtk_label_new (_("CIN / Passport:"));
  gtk_widget_show (labelCIN);
  gtk_fixed_put (GTK_FIXED (fixed2), labelCIN, 368, 168);
  gtk_widget_set_size_request (labelCIN, 144, 32);

  labelNom = gtk_label_new (_("Nom de l'ouvrier:"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed2), labelNom, 352, 128);
  gtk_widget_set_size_request (labelNom, 152, 32);

  entryUser = gtk_entry_new ();
  gtk_widget_show (entryUser);
  gtk_fixed_put (GTK_FIXED (fixed2), entryUser, 568, 272);
  gtk_widget_set_size_request (entryUser, 176, 32);
  gtk_entry_set_max_length (GTK_ENTRY (entryUser), 12);
  gtk_entry_set_text (GTK_ENTRY (entryUser), _("Username"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUser), 8226);

  labelUser = gtk_label_new (_("Nom d'utilisateur:"));
  gtk_widget_show (labelUser);
  gtk_fixed_put (GTK_FIXED (fixed2), labelUser, 360, 264);
  gtk_widget_set_size_request (labelUser, 152, 40);

  spinbuttonJT_adj = gtk_adjustment_new (5, 1, 6, 1, 10, 10);
  spinbuttonJT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJT_adj), 1, 0);
  gtk_widget_show (spinbuttonJT);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonJT, 568, 384);
  gtk_widget_set_size_request (spinbuttonJT, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbuttonJT), TRUE);

  labelDN = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (labelDN);
  gtk_fixed_put (GTK_FIXED (fixed2), labelDN, 312, 208);
  gtk_widget_set_size_request (labelDN, 232, 32);

  spinbuttonJJDN_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  spinbuttonJJDN = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJJDN_adj), 1, 0);
  gtk_widget_show (spinbuttonJJDN);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonJJDN, 568, 224);
  gtk_widget_set_size_request (spinbuttonJJDN, 60, 27);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spinbuttonJJDN), GTK_UPDATE_IF_VALID);

  spinbuttonMDN_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  spinbuttonMDN = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMDN_adj), 1, 0);
  gtk_widget_show (spinbuttonMDN);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonMDN, 640, 224);
  gtk_widget_set_size_request (spinbuttonMDN, 60, 27);

  spinbuttonADN_adj = gtk_adjustment_new (0, 1950, 2020, 1, 10, 10);
  spinbuttonADN = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonADN_adj), 1, 0);
  gtk_widget_show (spinbuttonADN);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonADN, 712, 224);
  gtk_widget_set_size_request (spinbuttonADN, 60, 27);

  spinbuttonJRec_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  spinbuttonJRec = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJRec_adj), 1, 0);
  gtk_widget_show (spinbuttonJRec);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonJRec, 568, 432);
  gtk_widget_set_size_request (spinbuttonJRec, 60, 27);

  spinbuttonMRec_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  spinbuttonMRec = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMRec_adj), 1, 0);
  gtk_widget_show (spinbuttonMRec);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonMRec, 648, 432);
  gtk_widget_set_size_request (spinbuttonMRec, 60, 27);

  spinbuttonARec_adj = gtk_adjustment_new (0, 1950, 2020, 1, 10, 10);
  spinbuttonARec = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonARec_adj), 1, 0);
  gtk_widget_show (spinbuttonARec);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonARec, 720, 432);
  gtk_widget_set_size_request (spinbuttonARec, 60, 27);

  labelTitle = gtk_label_new (Q_("Ajout des ouvriers"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed2), labelTitle, 504, 40);
  gtk_widget_set_size_request (labelTitle, 288, 64);
  gtk_label_set_justify (GTK_LABEL (labelTitle), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (labelTitle), 0.5, 0.41);

  comboboxSpec = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxSpec);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxSpec, 568, 320);
  gtk_widget_set_size_request (comboboxSpec, 272, 48);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxSpec), _("Agriculture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxSpec), _("Troupeaux"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxSpec), _("Equipements_agricoles"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxSpec), _("Capteurs"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxSpec), _("Ressources"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxSpec), _("Clients"));

  labelSpecial = gtk_label_new (_("Votre Specialit\303\251:"));
  gtk_widget_show (labelSpecial);
  gtk_fixed_put (GTK_FIXED (fixed2), labelSpecial, 376, 328);
  gtk_widget_set_size_request (labelSpecial, 144, 32);

  labelJT = gtk_label_new (_("Jours de travail:"));
  gtk_widget_show (labelJT);
  gtk_fixed_put (GTK_FIXED (fixed2), labelJT, 376, 384);
  gtk_widget_set_size_request (labelJT, 144, 32);

  checkbuttonLundi_o = gtk_check_button_new_with_mnemonic (_("Lundi"));
  gtk_widget_show (checkbuttonLundi_o);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonLundi_o, 648, 384);
  gtk_widget_set_size_request (checkbuttonLundi_o, 72, 24);

  checkbuttonMardi_o = gtk_check_button_new_with_mnemonic (_("Mardi"));
  gtk_widget_show (checkbuttonMardi_o);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonMardi_o, 712, 384);
  gtk_widget_set_size_request (checkbuttonMardi_o, 80, 24);

  checkbuttonMercredi_o = gtk_check_button_new_with_mnemonic (_("Mercredi"));
  gtk_widget_show (checkbuttonMercredi_o);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonMercredi_o, 792, 384);
  gtk_widget_set_size_request (checkbuttonMercredi_o, 96, 24);

  checkbuttonJeudi_o = gtk_check_button_new_with_mnemonic (_("Jeudi"));
  gtk_widget_show (checkbuttonJeudi_o);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonJeudi_o, 880, 384);
  gtk_widget_set_size_request (checkbuttonJeudi_o, 72, 24);

  checkbuttonVendredi_o = gtk_check_button_new_with_mnemonic (_("Vendredi"));
  gtk_widget_show (checkbuttonVendredi_o);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonVendredi_o, 944, 384);
  gtk_widget_set_size_request (checkbuttonVendredi_o, 96, 24);

  checkbuttonSamedi_o = gtk_check_button_new_with_mnemonic (_("Samedi"));
  gtk_widget_show (checkbuttonSamedi_o);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonSamedi_o, 1040, 384);
  gtk_widget_set_size_request (checkbuttonSamedi_o, 80, 24);

  checkbuttonDimanche_o = gtk_check_button_new_with_mnemonic (_("Dimanche"));
  gtk_widget_show (checkbuttonDimanche_o);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonDimanche_o, 1120, 384);
  gtk_widget_set_size_request (checkbuttonDimanche_o, 120, 24);

  labelRec = gtk_label_new (_("Date de recrutement:"));
  gtk_widget_show (labelRec);
  gtk_fixed_put (GTK_FIXED (fixed2), labelRec, 360, 432);
  gtk_widget_set_size_request (labelRec, 160, 24);

  labelGenre = gtk_label_new (_("Genre:"));
  gtk_widget_show (labelGenre);
  gtk_fixed_put (GTK_FIXED (fixed2), labelGenre, 440, 472);
  gtk_widget_set_size_request (labelGenre, 88, 32);

  radiobuttonH_o = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonH_o);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonH_o, 568, 480);
  gtk_widget_set_size_request (radiobuttonH_o, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonH_o), radiobuttonH_o_group);
  radiobuttonH_o_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonH_o));

  radiobuttonF_o = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonF_o);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonF_o, 680, 480);
  gtk_widget_set_size_request (radiobuttonF_o, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonF_o), radiobuttonH_o_group);
  radiobuttonH_o_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonF_o));

  buttonInscri_o = gtk_button_new ();
  gtk_widget_show (buttonInscri_o);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonInscri_o, 600, 528);
  gtk_widget_set_size_request (buttonInscri_o, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonInscri_o), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Inscrire"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox3), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) checkbuttonLundi_o, "toggled",
                    G_CALLBACK (on_checkbuttonLundi_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonMardi_o, "toggled",
                    G_CALLBACK (on_checkbuttonMardi_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonMercredi_o, "toggled",
                    G_CALLBACK (on_checkbuttonMercredi_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonJeudi_o, "toggled",
                    G_CALLBACK (on_checkbuttonJeudi_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonVendredi_o, "toggled",
                    G_CALLBACK (on_checkbuttonVendredi_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonSamedi_o, "toggled",
                    G_CALLBACK (on_checkbuttonSamedi_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonDimanche_o, "toggled",
                    G_CALLBACK (on_checkbuttonDimanche_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonH_o, "toggled",
                    G_CALLBACK (on_radiobuttonH_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonF_o, "toggled",
                    G_CALLBACK (on_radiobuttonF_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonInscri_o, "clicked",
                    G_CALLBACK (on_buttonInscri_o_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_o, Ajout_o, "Ajout_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajout_o, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (Ajout_o, entryCIN, "entryCIN");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelDNremarque, "labelDNremarque");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelCIN, "labelCIN");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (Ajout_o, entryUser, "entryUser");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelUser, "labelUser");
  GLADE_HOOKUP_OBJECT (Ajout_o, spinbuttonJT, "spinbuttonJT");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelDN, "labelDN");
  GLADE_HOOKUP_OBJECT (Ajout_o, spinbuttonJJDN, "spinbuttonJJDN");
  GLADE_HOOKUP_OBJECT (Ajout_o, spinbuttonMDN, "spinbuttonMDN");
  GLADE_HOOKUP_OBJECT (Ajout_o, spinbuttonADN, "spinbuttonADN");
  GLADE_HOOKUP_OBJECT (Ajout_o, spinbuttonJRec, "spinbuttonJRec");
  GLADE_HOOKUP_OBJECT (Ajout_o, spinbuttonMRec, "spinbuttonMRec");
  GLADE_HOOKUP_OBJECT (Ajout_o, spinbuttonARec, "spinbuttonARec");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelTitle, "labelTitle");
  GLADE_HOOKUP_OBJECT (Ajout_o, comboboxSpec, "comboboxSpec");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelSpecial, "labelSpecial");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelJT, "labelJT");
  GLADE_HOOKUP_OBJECT (Ajout_o, checkbuttonLundi_o, "checkbuttonLundi_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, checkbuttonMardi_o, "checkbuttonMardi_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, checkbuttonMercredi_o, "checkbuttonMercredi_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, checkbuttonJeudi_o, "checkbuttonJeudi_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, checkbuttonVendredi_o, "checkbuttonVendredi_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, checkbuttonSamedi_o, "checkbuttonSamedi_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, checkbuttonDimanche_o, "checkbuttonDimanche_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelRec, "labelRec");
  GLADE_HOOKUP_OBJECT (Ajout_o, labelGenre, "labelGenre");
  GLADE_HOOKUP_OBJECT (Ajout_o, radiobuttonH_o, "radiobuttonH_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, radiobuttonF_o, "radiobuttonF_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, buttonInscri_o, "buttonInscri_o");
  GLADE_HOOKUP_OBJECT (Ajout_o, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Ajout_o, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Ajout_o, image3, "image3");
  GLADE_HOOKUP_OBJECT (Ajout_o, label18, "label18");

  return Ajout_o;
}

GtkWidget*
create_Modification_o (void)
{
  GtkWidget *Modification_o;
  GtkWidget *fixed3;
  GtkWidget *entryid;
  GtkWidget *labelchamp;
  GtkWidget *labelid;
  GtkWidget *entryModif;
  GtkWidget *labelTitle;
  GtkWidget *labelModif;
  GtkWidget *buttonModifier_o;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label13;
  GtkWidget *comboboxChampModif;
  GtkWidget *buttonGestion_o;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label44;
  GtkWidget *labelResultat;

  Modification_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modification_o), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Modification_o), fixed3);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed3), entryid, 536, 168);
  gtk_widget_set_size_request (entryid, 312, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  labelchamp = gtk_label_new (_("Champ \303\240 modifier:"));
  gtk_widget_show (labelchamp);
  gtk_fixed_put (GTK_FIXED (fixed3), labelchamp, 368, 216);
  gtk_widget_set_size_request (labelchamp, 176, 40);

  labelid = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (labelid);
  gtk_fixed_put (GTK_FIXED (fixed3), labelid, 416, 160);
  gtk_widget_set_size_request (labelid, 128, 56);

  entryModif = gtk_entry_new ();
  gtk_widget_show (entryModif);
  gtk_fixed_put (GTK_FIXED (fixed3), entryModif, 536, 280);
  gtk_widget_set_size_request (entryModif, 312, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModif), 8226);

  labelTitle = gtk_label_new (_("Modification"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed3), labelTitle, 544, 24);
  gtk_widget_set_size_request (labelTitle, 216, 80);

  labelModif = gtk_label_new (_("Modification \303\240 faire:"));
  gtk_widget_show (labelModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelModif, 336, 248);
  gtk_widget_set_size_request (labelModif, 224, 88);

  buttonModifier_o = gtk_button_new ();
  gtk_widget_show (buttonModifier_o);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonModifier_o, 600, 336);
  gtk_widget_set_size_request (buttonModifier_o, 112, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonModifier_o), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox1), label13, FALSE, FALSE, 0);

  comboboxChampModif = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxChampModif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxChampModif, 536, 224);
  gtk_widget_set_size_request (comboboxChampModif, 312, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChampModif), _("Nom"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChampModif), _("Identifiant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChampModif), _("Specialite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxChampModif), _("Nombre de jours"));

  buttonGestion_o = gtk_button_new ();
  gtk_widget_show (buttonGestion_o);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestion_o, 576, 496);
  gtk_widget_set_size_request (buttonGestion_o, 176, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonGestion_o), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Gestion Compl\303\251te"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox8), label44, FALSE, FALSE, 0);

  labelResultat = gtk_label_new (_("Message de r\303\251sultat"));
  gtk_widget_show (labelResultat);
  gtk_fixed_put (GTK_FIXED (fixed3), labelResultat, 320, 400);
  gtk_widget_set_size_request (labelResultat, 672, 96);

  g_signal_connect ((gpointer) buttonModifier_o, "clicked",
                    G_CALLBACK (on_buttonModifier_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestion_o, "clicked",
                    G_CALLBACK (on_buttonGestion_o_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modification_o, Modification_o, "Modification_o");
  GLADE_HOOKUP_OBJECT (Modification_o, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Modification_o, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (Modification_o, labelchamp, "labelchamp");
  GLADE_HOOKUP_OBJECT (Modification_o, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (Modification_o, entryModif, "entryModif");
  GLADE_HOOKUP_OBJECT (Modification_o, labelTitle, "labelTitle");
  GLADE_HOOKUP_OBJECT (Modification_o, labelModif, "labelModif");
  GLADE_HOOKUP_OBJECT (Modification_o, buttonModifier_o, "buttonModifier_o");
  GLADE_HOOKUP_OBJECT (Modification_o, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Modification_o, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Modification_o, image1, "image1");
  GLADE_HOOKUP_OBJECT (Modification_o, label13, "label13");
  GLADE_HOOKUP_OBJECT (Modification_o, comboboxChampModif, "comboboxChampModif");
  GLADE_HOOKUP_OBJECT (Modification_o, buttonGestion_o, "buttonGestion_o");
  GLADE_HOOKUP_OBJECT (Modification_o, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Modification_o, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Modification_o, image8, "image8");
  GLADE_HOOKUP_OBJECT (Modification_o, label44, "label44");
  GLADE_HOOKUP_OBJECT (Modification_o, labelResultat, "labelResultat");

  return Modification_o;
}

GtkWidget*
create_Suppression_o (void)
{
  GtkWidget *Suppression_o;
  GtkWidget *fixed4;
  GtkWidget *labelTitle;
  GtkWidget *labelid;
  GtkWidget *entryId;
  GtkWidget *buttonSupprimmer_o;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label17;

  Suppression_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Suppression_o), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Suppression_o), fixed4);

  labelTitle = gtk_label_new (_("Suppression"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed4), labelTitle, 608, 64);
  gtk_widget_set_size_request (labelTitle, 88, 48);

  labelid = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (labelid);
  gtk_fixed_put (GTK_FIXED (fixed4), labelid, 440, 168);
  gtk_widget_set_size_request (labelid, 96, 40);

  entryId = gtk_entry_new ();
  gtk_widget_show (entryId);
  gtk_fixed_put (GTK_FIXED (fixed4), entryId, 592, 176);
  gtk_widget_set_size_request (entryId, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryId), 8226);

  buttonSupprimmer_o = gtk_button_new ();
  gtk_widget_show (buttonSupprimmer_o);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonSupprimmer_o, 600, 256);
  gtk_widget_set_size_request (buttonSupprimmer_o, 112, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonSupprimmer_o), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox2), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonSupprimmer_o, "clicked",
                    G_CALLBACK (on_buttonSupprimmer_o_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Suppression_o, Suppression_o, "Suppression_o");
  GLADE_HOOKUP_OBJECT (Suppression_o, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Suppression_o, labelTitle, "labelTitle");
  GLADE_HOOKUP_OBJECT (Suppression_o, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (Suppression_o, entryId, "entryId");
  GLADE_HOOKUP_OBJECT (Suppression_o, buttonSupprimmer_o, "buttonSupprimmer_o");
  GLADE_HOOKUP_OBJECT (Suppression_o, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Suppression_o, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Suppression_o, image2, "image2");
  GLADE_HOOKUP_OBJECT (Suppression_o, label17, "label17");

  return Suppression_o;
}

GtkWidget*
create_Affichage_o (void)
{
  GtkWidget *Affichage_o;
  GtkWidget *fixed5;
  GtkWidget *treeview3;
  GtkWidget *labelTitle;

  Affichage_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Affichage_o), _("window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Affichage_o), fixed5);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview3, 152, 104);
  gtk_widget_set_size_request (treeview3, 1024, 392);

  labelTitle = gtk_label_new (_("Affichage"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed5), labelTitle, 616, 56);
  gtk_widget_set_size_request (labelTitle, 96, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Affichage_o, Affichage_o, "Affichage_o");
  GLADE_HOOKUP_OBJECT (Affichage_o, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Affichage_o, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Affichage_o, labelTitle, "labelTitle");

  return Affichage_o;
}

GtkWidget*
create_Recherche_o (void)
{
  GtkWidget *Recherche_o;
  GtkWidget *fixed6;
  GtkWidget *labelChamp;
  GtkWidget *entryInfo;
  GtkWidget *labelTitle;
  GtkWidget *buttonRecherche_o;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label27;
  GtkWidget *comboboxentryChamp;
  GtkWidget *labelInformation;

  Recherche_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Recherche_o), _("window6"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Recherche_o), fixed6);

  labelChamp = gtk_label_new (_("Champ"));
  gtk_widget_show (labelChamp);
  gtk_fixed_put (GTK_FIXED (fixed6), labelChamp, 488, 128);
  gtk_widget_set_size_request (labelChamp, 49, 17);

  entryInfo = gtk_entry_new ();
  gtk_widget_show (entryInfo);
  gtk_fixed_put (GTK_FIXED (fixed6), entryInfo, 592, 176);
  gtk_widget_set_size_request (entryInfo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryInfo), 8226);

  labelTitle = gtk_label_new (_("Rechercher"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed6), labelTitle, 608, 72);
  gtk_widget_set_size_request (labelTitle, 96, 32);

  buttonRecherche_o = gtk_button_new ();
  gtk_widget_show (buttonRecherche_o);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonRecherche_o, 600, 232);
  gtk_widget_set_size_request (buttonRecherche_o, 120, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonRecherche_o), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox5), label27, FALSE, FALSE, 0);

  comboboxentryChamp = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryChamp);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentryChamp, 592, 120);
  gtk_widget_set_size_request (comboboxentryChamp, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryChamp), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryChamp), _("Identifiant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryChamp), _("Nom"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryChamp), _("CIN"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryChamp), _("Sp\303\251cialit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryChamp), _("Jours de travail"));

  labelInformation = gtk_label_new (_("Information"));
  gtk_widget_show (labelInformation);
  gtk_fixed_put (GTK_FIXED (fixed6), labelInformation, 448, 176);
  gtk_widget_set_size_request (labelInformation, 104, 32);

  g_signal_connect ((gpointer) buttonRecherche_o, "clicked",
                    G_CALLBACK (on_buttonRecherche_o_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Recherche_o, Recherche_o, "Recherche_o");
  GLADE_HOOKUP_OBJECT (Recherche_o, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Recherche_o, labelChamp, "labelChamp");
  GLADE_HOOKUP_OBJECT (Recherche_o, entryInfo, "entryInfo");
  GLADE_HOOKUP_OBJECT (Recherche_o, labelTitle, "labelTitle");
  GLADE_HOOKUP_OBJECT (Recherche_o, buttonRecherche_o, "buttonRecherche_o");
  GLADE_HOOKUP_OBJECT (Recherche_o, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Recherche_o, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Recherche_o, image5, "image5");
  GLADE_HOOKUP_OBJECT (Recherche_o, label27, "label27");
  GLADE_HOOKUP_OBJECT (Recherche_o, comboboxentryChamp, "comboboxentryChamp");
  GLADE_HOOKUP_OBJECT (Recherche_o, labelInformation, "labelInformation");

  return Recherche_o;
}

GtkWidget*
create_Controle_o (void)
{
  GtkWidget *Controle_o;
  GtkWidget *fixed7;
  GtkWidget *entryid;
  GtkWidget *labelTitle;
  GtkWidget *labelid;
  GtkWidget *labelConfirm;
  GtkWidget *radiobuttonOui_o;
  GSList *radiobuttonOui_o_group = NULL;
  GtkWidget *radiobuttonNon_o;
  GtkObject *spinbuttonJC_adj;
  GtkWidget *spinbuttonJC;
  GtkObject *spinbuttonMC_adj;
  GtkWidget *spinbuttonMC;
  GtkWidget *labelJ;
  GtkObject *spinbuttonMA_adj;
  GtkWidget *spinbuttonMA;
  GtkWidget *envoi_o;

  Controle_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Controle_o), _("window7"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Controle_o), fixed7);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed7), entryid, 568, 152);
  gtk_widget_set_size_request (entryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  labelTitle = gtk_label_new (_("Heures de Travail"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed7), labelTitle, 568, 64);
  gtk_widget_set_size_request (labelTitle, 168, 56);

  labelid = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelid);
  gtk_fixed_put (GTK_FIXED (fixed7), labelid, 448, 152);
  gtk_widget_set_size_request (labelid, 80, 32);

  labelConfirm = gtk_label_new (_("a travaille?"));
  gtk_widget_show (labelConfirm);
  gtk_fixed_put (GTK_FIXED (fixed7), labelConfirm, 448, 280);
  gtk_widget_set_size_request (labelConfirm, 88, 32);

  radiobuttonOui_o = gtk_radio_button_new_with_mnemonic (NULL, _("Oui"));
  gtk_widget_show (radiobuttonOui_o);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobuttonOui_o, 568, 288);
  gtk_widget_set_size_request (radiobuttonOui_o, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonOui_o), radiobuttonOui_o_group);
  radiobuttonOui_o_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonOui_o));

  radiobuttonNon_o = gtk_radio_button_new_with_mnemonic (NULL, _("Non"));
  gtk_widget_show (radiobuttonNon_o);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobuttonNon_o, 728, 288);
  gtk_widget_set_size_request (radiobuttonNon_o, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonNon_o), radiobuttonOui_o_group);
  radiobuttonOui_o_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonNon_o));

  spinbuttonJC_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  spinbuttonJC = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJC_adj), 1, 0);
  gtk_widget_show (spinbuttonJC);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonJC, 568, 224);
  gtk_widget_set_size_request (spinbuttonJC, 60, 27);

  spinbuttonMC_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  spinbuttonMC = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMC_adj), 1, 0);
  gtk_widget_show (spinbuttonMC);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonMC, 648, 224);
  gtk_widget_set_size_request (spinbuttonMC, 60, 27);

  labelJ = gtk_label_new (_("Jour"));
  gtk_widget_show (labelJ);
  gtk_fixed_put (GTK_FIXED (fixed7), labelJ, 464, 232);
  gtk_widget_set_size_request (labelJ, 49, 17);

  spinbuttonMA_adj = gtk_adjustment_new (0, 2020, 3000, 1, 10, 10);
  spinbuttonMA = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMA_adj), 1, 0);
  gtk_widget_show (spinbuttonMA);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonMA, 728, 224);
  gtk_widget_set_size_request (spinbuttonMA, 60, 27);

  envoi_o = gtk_button_new_with_mnemonic (_("Reporter"));
  gtk_widget_show (envoi_o);
  gtk_fixed_put (GTK_FIXED (fixed7), envoi_o, 600, 360);
  gtk_widget_set_size_request (envoi_o, 96, 40);

  g_signal_connect ((gpointer) radiobuttonOui_o, "toggled",
                    G_CALLBACK (on_radiobuttonOui_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonNon_o, "toggled",
                    G_CALLBACK (on_radiobuttonNon_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) envoi_o, "clicked",
                    G_CALLBACK (on_envoi_o_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Controle_o, Controle_o, "Controle_o");
  GLADE_HOOKUP_OBJECT (Controle_o, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Controle_o, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (Controle_o, labelTitle, "labelTitle");
  GLADE_HOOKUP_OBJECT (Controle_o, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (Controle_o, labelConfirm, "labelConfirm");
  GLADE_HOOKUP_OBJECT (Controle_o, radiobuttonOui_o, "radiobuttonOui_o");
  GLADE_HOOKUP_OBJECT (Controle_o, radiobuttonNon_o, "radiobuttonNon_o");
  GLADE_HOOKUP_OBJECT (Controle_o, spinbuttonJC, "spinbuttonJC");
  GLADE_HOOKUP_OBJECT (Controle_o, spinbuttonMC, "spinbuttonMC");
  GLADE_HOOKUP_OBJECT (Controle_o, labelJ, "labelJ");
  GLADE_HOOKUP_OBJECT (Controle_o, spinbuttonMA, "spinbuttonMA");
  GLADE_HOOKUP_OBJECT (Controle_o, envoi_o, "envoi_o");

  return Controle_o;
}

GtkWidget*
create_Resultat_o (void)
{
  GtkWidget *Resultat_o;
  GtkWidget *fixed8;
  GtkWidget *treeview5;
  GtkWidget *labelTitle;

  Resultat_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Resultat_o), _("window6"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Resultat_o), fixed8);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview5, 192, 88);
  gtk_widget_set_size_request (treeview5, 984, 408);

  labelTitle = gtk_label_new (_("R\303\251sultats de recherhce:"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed8), labelTitle, 512, 24);
  gtk_widget_set_size_request (labelTitle, 256, 72);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Resultat_o, Resultat_o, "Resultat_o");
  GLADE_HOOKUP_OBJECT (Resultat_o, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Resultat_o, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (Resultat_o, labelTitle, "labelTitle");

  return Resultat_o;
}

GtkWidget*
create_Gestion_des_ouvriers_o (void)
{
  GtkWidget *Gestion_des_ouvriers_o;
  GtkWidget *fixed9;
  GtkWidget *entryNewNom;
  GtkWidget *entryNewCIN;
  GtkWidget *entryNewUser;
  GtkObject *spinbuttonNewJT_adj;
  GtkWidget *spinbuttonNewJT;
  GtkObject *spinbuttonNewJJ_adj;
  GtkWidget *spinbuttonNewJJ;
  GtkObject *spinbuttonNewMM_adj;
  GtkWidget *spinbuttonNewMM;
  GtkObject *spinbuttonNewAAAA_adj;
  GtkWidget *spinbuttonNewAAAA;
  GtkObject *spinbuttonNewDRJJ_adj;
  GtkWidget *spinbuttonNewDRJJ;
  GtkObject *spinbuttonNewDRMM_adj;
  GtkWidget *spinbuttonNewDRMM;
  GtkObject *spinbuttonNewDRAAAA_adj;
  GtkWidget *spinbuttonNewDRAAAA;
  GtkWidget *radiobuttonNewF_o;
  GSList *radiobuttonNewF_o_group = NULL;
  GtkWidget *buttonFull_Modif_o;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label41;
  GtkWidget *treeview6_o;
  GtkWidget *labelMessage;
  GtkWidget *buttonFinalDelete_o;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label43;
  GtkWidget *labelTitle;
  GtkWidget *checkbuttonDelete_o;
  GtkWidget *labelNom;
  GtkWidget *labelDN;
  GtkWidget *labelCIN;
  GtkWidget *labelUser;
  GtkWidget *labelNbre;
  GtkWidget *labelSpec;
  GtkWidget *labelDR;
  GtkWidget *labelGenre;
  GtkWidget *button_Confirm_Modif_o;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label45;
  GtkWidget *radiobuttonNewH_o;
  GtkWidget *comboboxNewSpec;

  Gestion_des_ouvriers_o = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_ouvriers_o), _("window1"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Gestion_des_ouvriers_o), fixed9);

  entryNewNom = gtk_entry_new ();
  gtk_widget_show (entryNewNom);
  gtk_fixed_put (GTK_FIXED (fixed9), entryNewNom, 1120, 144);
  gtk_widget_set_size_request (entryNewNom, 136, 32);
  gtk_entry_set_max_length (GTK_ENTRY (entryNewNom), 100);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNewNom), 46);

  entryNewCIN = gtk_entry_new ();
  gtk_widget_show (entryNewCIN);
  gtk_fixed_put (GTK_FIXED (fixed9), entryNewCIN, 1120, 184);
  gtk_widget_set_size_request (entryNewCIN, 136, 32);
  gtk_entry_set_max_length (GTK_ENTRY (entryNewCIN), 12);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNewCIN), 8226);

  entryNewUser = gtk_entry_new ();
  gtk_widget_show (entryNewUser);
  gtk_fixed_put (GTK_FIXED (fixed9), entryNewUser, 1136, 288);
  gtk_widget_set_size_request (entryNewUser, 128, 32);
  gtk_entry_set_max_length (GTK_ENTRY (entryNewUser), 12);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNewUser), 8226);

  spinbuttonNewJT_adj = gtk_adjustment_new (5, 1, 6, 1, 10, 10);
  spinbuttonNewJT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNewJT_adj), 1, 0);
  gtk_widget_show (spinbuttonNewJT);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonNewJT, 1168, 328);
  gtk_widget_set_size_request (spinbuttonNewJT, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbuttonNewJT), TRUE);

  spinbuttonNewJJ_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  spinbuttonNewJJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNewJJ_adj), 1, 0);
  gtk_widget_show (spinbuttonNewJJ);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonNewJJ, 1008, 248);
  gtk_widget_set_size_request (spinbuttonNewJJ, 60, 27);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spinbuttonNewJJ), GTK_UPDATE_IF_VALID);

  spinbuttonNewMM_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  spinbuttonNewMM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNewMM_adj), 1, 0);
  gtk_widget_show (spinbuttonNewMM);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonNewMM, 1088, 248);
  gtk_widget_set_size_request (spinbuttonNewMM, 60, 27);

  spinbuttonNewAAAA_adj = gtk_adjustment_new (0, 1950, 2020, 1, 10, 10);
  spinbuttonNewAAAA = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNewAAAA_adj), 1, 0);
  gtk_widget_show (spinbuttonNewAAAA);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonNewAAAA, 1168, 248);
  gtk_widget_set_size_request (spinbuttonNewAAAA, 60, 27);

  spinbuttonNewDRJJ_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  spinbuttonNewDRJJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNewDRJJ_adj), 1, 0);
  gtk_widget_show (spinbuttonNewDRJJ);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonNewDRJJ, 1008, 448);
  gtk_widget_set_size_request (spinbuttonNewDRJJ, 60, 27);

  spinbuttonNewDRMM_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  spinbuttonNewDRMM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNewDRMM_adj), 1, 0);
  gtk_widget_show (spinbuttonNewDRMM);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonNewDRMM, 1088, 448);
  gtk_widget_set_size_request (spinbuttonNewDRMM, 60, 27);

  spinbuttonNewDRAAAA_adj = gtk_adjustment_new (0, 1950, 2020, 1, 10, 10);
  spinbuttonNewDRAAAA = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNewDRAAAA_adj), 1, 0);
  gtk_widget_show (spinbuttonNewDRAAAA);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonNewDRAAAA, 1168, 448);
  gtk_widget_set_size_request (spinbuttonNewDRAAAA, 60, 27);

  radiobuttonNewF_o = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonNewF_o);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobuttonNewF_o, 1088, 520);
  gtk_widget_set_size_request (radiobuttonNewF_o, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonNewF_o), radiobuttonNewF_o_group);
  radiobuttonNewF_o_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonNewF_o));

  buttonFull_Modif_o = gtk_button_new ();
  gtk_widget_show (buttonFull_Modif_o);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonFull_Modif_o, 1104, 552);
  gtk_widget_set_size_request (buttonFull_Modif_o, 112, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonFull_Modif_o), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox6), label41, FALSE, FALSE, 0);

  treeview6_o = gtk_tree_view_new ();
  gtk_widget_show (treeview6_o);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview6_o, 16, 104);
  gtk_widget_set_size_request (treeview6_o, 856, 360);

  labelMessage = gtk_label_new (_("S\303\251lectionnez les champs \303\240 modifier et entrez vos modificaitons:"));
  gtk_widget_show (labelMessage);
  gtk_fixed_put (GTK_FIXED (fixed9), labelMessage, 984, 72);
  gtk_widget_set_size_request (labelMessage, 288, 64);
  gtk_label_set_justify (GTK_LABEL (labelMessage), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (labelMessage), TRUE);

  buttonFinalDelete_o = gtk_button_new ();
  gtk_widget_show (buttonFinalDelete_o);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonFinalDelete_o, 376, 544);
  gtk_widget_set_size_request (buttonFinalDelete_o, 112, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonFinalDelete_o), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox7), label43, FALSE, FALSE, 0);

  labelTitle = gtk_label_new (Q_("Gestion des ouvriers"));
  gtk_widget_show (labelTitle);
  gtk_fixed_put (GTK_FIXED (fixed9), labelTitle, 504, 40);
  gtk_widget_set_size_request (labelTitle, 288, 64);
  gtk_label_set_justify (GTK_LABEL (labelTitle), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (labelTitle), 0.5, 0.41);

  checkbuttonDelete_o = gtk_check_button_new_with_mnemonic (_("Voulez vous supprimer cet ouvrier?"));
  gtk_widget_show (checkbuttonDelete_o);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbuttonDelete_o, 288, 504);
  gtk_widget_set_size_request (checkbuttonDelete_o, 264, 32);

  labelNom = gtk_label_new (_("Nom"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed9), labelNom, 1008, 152);
  gtk_widget_set_size_request (labelNom, 49, 17);

  labelDN = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (labelDN);
  gtk_fixed_put (GTK_FIXED (fixed9), labelDN, 1056, 216);
  gtk_widget_set_size_request (labelDN, 128, 24);

  labelCIN = gtk_label_new (_("CIN"));
  gtk_widget_show (labelCIN);
  gtk_fixed_put (GTK_FIXED (fixed9), labelCIN, 1008, 192);
  gtk_widget_set_size_request (labelCIN, 49, 17);

  labelUser = gtk_label_new (_("Nom d'utilisateur"));
  gtk_widget_show (labelUser);
  gtk_fixed_put (GTK_FIXED (fixed9), labelUser, 960, 288);
  gtk_widget_set_size_request (labelUser, 153, 32);

  labelNbre = gtk_label_new (_("Nombre de jours de travail"));
  gtk_widget_show (labelNbre);
  gtk_fixed_put (GTK_FIXED (fixed9), labelNbre, 936, 328);
  gtk_widget_set_size_request (labelNbre, 200, 32);

  labelSpec = gtk_label_new (_("Specialit\303\251"));
  gtk_widget_show (labelSpec);
  gtk_fixed_put (GTK_FIXED (fixed9), labelSpec, 992, 368);
  gtk_widget_set_size_request (labelSpec, 96, 32);

  labelDR = gtk_label_new (_("Date de recrutement"));
  gtk_widget_show (labelDR);
  gtk_fixed_put (GTK_FIXED (fixed9), labelDR, 1056, 416);
  gtk_widget_set_size_request (labelDR, 152, 32);

  labelGenre = gtk_label_new (_("Genre"));
  gtk_widget_show (labelGenre);
  gtk_fixed_put (GTK_FIXED (fixed9), labelGenre, 1024, 504);
  gtk_widget_set_size_request (labelGenre, 49, 17);

  button_Confirm_Modif_o = gtk_button_new ();
  gtk_widget_show (button_Confirm_Modif_o);
  gtk_fixed_put (GTK_FIXED (fixed9), button_Confirm_Modif_o, 688, 544);
  gtk_widget_set_size_request (button_Confirm_Modif_o, 128, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_Confirm_Modif_o), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Modifer"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox9), label45, FALSE, FALSE, 0);

  radiobuttonNewH_o = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonNewH_o);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobuttonNewH_o, 1088, 488);
  gtk_widget_set_size_request (radiobuttonNewH_o, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonNewH_o), radiobuttonNewF_o_group);
  radiobuttonNewF_o_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonNewH_o));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobuttonNewH_o), TRUE);

  comboboxNewSpec = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxNewSpec);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxNewSpec, 1136, 368);
  gtk_widget_set_size_request (comboboxNewSpec, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxNewSpec), _("Agriculture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxNewSpec), _("Troupeaux"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxNewSpec), _("Equipements_agricoles"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxNewSpec), _("Capteurs"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxNewSpec), _("Ressources"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxNewSpec), _("Clients"));

  g_signal_connect ((gpointer) radiobuttonNewF_o, "toggled",
                    G_CALLBACK (on_radiobuttonNewF_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonFull_Modif_o, "clicked",
                    G_CALLBACK (on_buttonFull_Modif_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview6_o, "row_activated",
                    G_CALLBACK (on_treeview6_o_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonFinalDelete_o, "clicked",
                    G_CALLBACK (on_buttonFinalDelete_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonDelete_o, "toggled",
                    G_CALLBACK (on_checkbuttonDelete_o_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_Confirm_Modif_o, "clicked",
                    G_CALLBACK (on_button_Confirm_Modif_o_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonNewH_o, "toggled",
                    G_CALLBACK (on_radiobuttonNewH_o_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_ouvriers_o, Gestion_des_ouvriers_o, "Gestion_des_ouvriers_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, entryNewNom, "entryNewNom");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, entryNewCIN, "entryNewCIN");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, entryNewUser, "entryNewUser");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, spinbuttonNewJT, "spinbuttonNewJT");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, spinbuttonNewJJ, "spinbuttonNewJJ");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, spinbuttonNewMM, "spinbuttonNewMM");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, spinbuttonNewAAAA, "spinbuttonNewAAAA");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, spinbuttonNewDRJJ, "spinbuttonNewDRJJ");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, spinbuttonNewDRMM, "spinbuttonNewDRMM");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, spinbuttonNewDRAAAA, "spinbuttonNewDRAAAA");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, radiobuttonNewF_o, "radiobuttonNewF_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, buttonFull_Modif_o, "buttonFull_Modif_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, image6, "image6");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, label41, "label41");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, treeview6_o, "treeview6_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelMessage, "labelMessage");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, buttonFinalDelete_o, "buttonFinalDelete_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, image7, "image7");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelTitle, "labelTitle");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, checkbuttonDelete_o, "checkbuttonDelete_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelDN, "labelDN");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelCIN, "labelCIN");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelUser, "labelUser");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelNbre, "labelNbre");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelSpec, "labelSpec");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelDR, "labelDR");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, labelGenre, "labelGenre");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, button_Confirm_Modif_o, "button_Confirm_Modif_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, image9, "image9");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, label45, "label45");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, radiobuttonNewH_o, "radiobuttonNewH_o");
  GLADE_HOOKUP_OBJECT (Gestion_des_ouvriers_o, comboboxNewSpec, "comboboxNewSpec");

  return Gestion_des_ouvriers_o;
}

