/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_generale (void);
GtkWidget* create_admin (void);
GtkWidget* create_ajout (void);
GtkWidget* create_employ__ (void);
GtkWidget* create_propri__taire (void);
GtkWidget* create_Gestion (void);
GtkWidget* create_partie2 (void);
GtkWidget* create_Moetez_1 (void);
GtkWidget* create_Moetez_2 (void);
GtkWidget* create_Hedi_1 (void);
GtkWidget* create_Hedi_2 (void);
GtkWidget* create_Souhir_1 (void);
GtkWidget* create_Souhir_2 (void);
GtkWidget* create_Achraf_1 (void);
GtkWidget* create_Achraf_2 (void);
GtkWidget* create_Rania_1 (void);
GtkWidget* create_Rania_2 (void);
GtkWidget* create_Interface_o (void);
GtkWidget* create_Ajout_o (void);
GtkWidget* create_Modification_o (void);
GtkWidget* create_Suppression_o (void);
GtkWidget* create_Affichage_o (void);
GtkWidget* create_Recherche_o (void);
GtkWidget* create_Controle_o (void);
GtkWidget* create_Resultat_o (void);
GtkWidget* create_Gestion_des_ouvriers_o (void);
GtkWidget* create_Gestion_des_plantes_p (void);
GtkWidget* create_fenetre_ajout_p (void);
GtkWidget* create_Rechercher_p (void);
GtkWidget* create_Modification_p (void);
GtkWidget* create_fenetre_afficher_p (void);
GtkWidget* create_Gestion_des_troupeaux_t (void);
GtkWidget* create_fenetre_ajout_t (void);
GtkWidget* create_Rechercher_t (void);
GtkWidget* create_Modification_t (void);
GtkWidget* create_fenetre_afficher_t (void);
GtkWidget* create_Gestion_des_capteurs_ca (void);
GtkWidget* create_fenetre_ajout_ca (void);
GtkWidget* create_Rechercher_ca (void);
GtkWidget* create_Modification_ca (void);
GtkWidget* create_fenetre_afficher_ca (void);
