/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Interface_o (void);
GtkWidget* create_Ajout_o (void);
GtkWidget* create_Modification_o (void);
GtkWidget* create_Suppression_o (void);
GtkWidget* create_Affichage_o (void);
GtkWidget* create_Recherche_o (void);
GtkWidget* create_Controle_o (void);
GtkWidget* create_Resultat_o (void);
GtkWidget* create_Gestion_des_ouvriers_o (void);
